# site settings
title: Circolino Hack
subtitle: a group of fantastic nerds
email: info@circolinohack.com
description: a group of fantastic nerds
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Circolino Hack
street_address: localhost
city:
state:
zip_code:
country: ":nerd_face:"
phone: 127.0.0.1

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/Circolinohack
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

# Plugins
plugins:
  - jemoji